Description: "The Dark Edge Lords of Code (TDELoC) Stack."
Resources:
  DarkInfrastructure:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - !Ref InfraInstanceSecurityGroup
        - !Ref SSHSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: TDLoC-Infrastructure
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DarkStaging:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref DefaultSecurityGroup
        - !Ref SSHSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: TDLoC-Staging
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DarkProd:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref DefaultSecurityGroup
        - !Ref SSHSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: TDLoC-Prod
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  SSHSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SSH Security Group
      GroupName: TDELoC-SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 198.255.180.29/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 54.160.51.6/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 44.207.13.147/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 44.208.120.75/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 3.234.39.123/32
        # - IpProtocol: tcp
        #   FromPort: 22
        #   ToPort: 22
        #   CidrIp: !GetAtt DarkInfrastructure.PublicIp
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  InfraInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Infrastructure SecurityGroup
      GroupName: TDELoC-Infrastructure
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8085
          ToPort: 8085
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DefaultSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Default SecurityGroup
      GroupName: TDELoC-Default
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8088
          ToPort: 8088
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"

Outputs:
  InfraPublicIP:
    Description: The public IP of DarkInfrastructure
    Value:  !GetAtt DarkInfrastructure.PublicIp
  InfraPublicDNS:
    Description: The public DNS Name of DarkInfrastructure
    Value:  !GetAtt DarkInfrastructure.PublicDnsName
  StagingPublicIP:
    Description: The public IP of DarkStaging
    Value:  !GetAtt DarkStaging.PublicIp
  StagingPublicDNS:
    Description: The public DNS Name of DarkStaging
    Value:  !GetAtt DarkStaging.PublicDnsName
  ProdPublicIP:
    Description: The public IP of DarkProd
    Value: !GetAtt DarkProd.PublicIp
  ProdPublicDNS:
    Description: The public DNS Name of DarkProd
    Value: !GetAtt DarkProd.PublicDnsName