---
- name: Install Docker and Docker-Compose
  hosts: docker

  tasks:

  - name: Apt Update
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name: docker-compose-plugin
      state: present

  - name: Install Python
    apt:
      name: python
      state: present
      
  - name: Install Docker
    pip:
      name: docker

  - name: Start Docker
    service:
      name: docker
      state: started