---
- name: Install Docker and Docker-Compose
  hosts: docker

  tasks:

  - name: Add Apt Repo
    ansible.builtin.apt_repository:
      repo: deb http://archive.ubuntu.com/ubuntu bionic universe
      state: present
      filename: docker-compose

  - name: Apt Update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install Docker-Compose
    ansible.builtin.apt:
      name: docker-compose
      state: present

  - name: Install Python
    ansible.builtin.apt:
      name: python
      state: present

  - name: install Python pip3
    ansible.builtin.apt:
      name: python3-pip

  - name: Install Docker
    ansible.builtin.pip:
      name: docker
      executable: pip3

  - name: Start Docker
    service:
      name: docker
      state: started