---
- name: Deploy Cloudformation Stack

  tasks:

  - name: Deploy Stack
    amazon.aws.cloudformation:
      stack_name: "TheDarkEdgeLordsofCode"
      state: present
      region: us-east-1
      template: "./cfm.yml"
      on_create_failure: DELETE
  
  - name: Get summary information about a stack
    amazon.aws.cloudformation_info:
      stack_name: "TheDarkEdgeLordsofCode"
    register: stackOutput

  - name: Assign new Infra Inventory
    add_host:
      name: "{{ stackOutput['cloudformation']['TheDarkEdgeLordsofCode']['stack_description']['outputs']['InfraPublicDNS'] }}"
      groups:
      - cfm
      - infra
  - name: Assign new Staging Inventory
    add_host:
      name: "{{ stackOutput['cloudformation']['TheDarkEdgeLordsofCode']['stack_description']['outputs']['StagingPublicDNS'] }}"
      groups: cfm
  - name: Assign new Prod Inventory
    add_host:
      name: "{{ stackOutput['cloudformation']['TheDarkEdgeLordsofCode']['stack_description']['outputs']['ProdPublicDNS'] }}"
      groups: cfm

- name: Deploy Docker & Docker Compose
  hosts: cfm

  tasks:

- name: Deploy Bamboo
  hosts: infra

  tasks:

