version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     logging:
       driver: "splunk"
       options:
        splunk-token: "f1b72e61-99a7-4ecf-b214-1eecfcb14e70"
        splunk-url: "https://prd-p-a598i.splunkcloud.com:8088/services/collector"
        splunk-insecureskipverify: "true"

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 8088:80
     restart: always
     volumes:
      - www_data:/var/www/html
     environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* SETTING ENV TYPE */
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
     logging:
      driver: "splunk"
      options:
        splunk-token: "f1b72e61-99a7-4ecf-b214-1eecfcb14e70"
        splunk-url: "https://prd-p-a598i.splunkcloud.com:8088/services/collector"
        splunk-insecureskipverify: "true"

volumes:
    db_data: {}
    www_data: {}
