Resources:
  DarkInfrastructure:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - !Ref InfraInstanceSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DarkStaging:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref DefaultSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DarkProd:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref DefaultSecurityGroup
      ImageId: ami-00a0e0b890ae17d65
      KeyName: Dark-Lords08
      AvailabilityZone: us-east-1a
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  InfraInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Infrastructure SecurityGroup
      GroupName: TDELoC-Infrastructure
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8085
          ToPort: 8085
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"
  DefaultSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Default SecurityGroup
      GroupName: TDELoC-Default
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8088
          ToPort: 8088
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "course"
          Value: "IEA"
        - Key: "cohort"
          Value: "8"

Outputs:
  InfraPublicIP:
    Description: The public IP of DarkInfrastructure
    Value:  !GetAtt DarkInfrastructure.PublicIp
  StagingPublicIP:
    Description: The public IP of DarkStaging
    Value:  !GetAtt DarkStaging.PublicIp
  ProdPublicIP:
    Description: The public IP of DarkProd
    Value: !GetAtt DarkProd.PublicIp