---
- name: Bamboo Install
  hosts: TDLoC-Infrastructure

  tasks:

  - name:
    community.docker.docker_volume:
      name: bambooVolume
      state: present

  - name:
    community.docker.docker_container:
      name: bamboo
      image: jrrickerson/capstone-bamboo
      state: started
      detach: true
      groups: docker
      restart_policy: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - bambooVolume:/var/atlassian/application-data/bamboo
      ports:
        - "54663:54663"
        - "8085:8085"
